# Generated by Django 4.1.7 on 2023-03-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_code', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1)),
                ('birth_day', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('primary_healthcare', models.CharField(max_length=200)),
                ('first_date_use', models.DateField()),
                ('last_date_use', models.DateField()),
            ],
        ),
    ]
